'use server';

/**
 * @fileOverview Analyzes Playwright test failure logs and suggests potential reasons for failure.
 *
 * - analyzeTestFailureLogs - A function that analyzes test failure logs and returns suggested reasons.
 * - AnalyzeTestFailureLogsInput - The input type for the analyzeTestFailureLogs function.
 * - AnalyzeTestFailureLogsOutput - The return type for the analyzeTestFailureLogs function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeTestFailureLogsInputSchema = z.object({
  errorLog: z
    .string()
    .describe('The error log generated by the Playwright test execution.'),
});
export type AnalyzeTestFailureLogsInput = z.infer<typeof AnalyzeTestFailureLogsInputSchema>;

const AnalyzeTestFailureLogsOutputSchema = z.object({
  suggestedReasons: z
    .string()
    .describe('The suggested reasons for the test failure based on the error log.'),
});
export type AnalyzeTestFailureLogsOutput = z.infer<typeof AnalyzeTestFailureLogsOutputSchema>;

export async function analyzeTestFailureLogs(
  input: AnalyzeTestFailureLogsInput
): Promise<AnalyzeTestFailureLogsOutput> {
  return analyzeTestFailureLogsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeTestFailureLogsPrompt',
  input: {schema: AnalyzeTestFailureLogsInputSchema},
  output: {schema: AnalyzeTestFailureLogsOutputSchema},
  prompt: `You are an expert software test engineer. You will analyze the error log from a Playwright test execution and suggest potential reasons for the failure.

Error Log:
{{{errorLog}}}

Suggest reasons for the failure:
`,
});

const analyzeTestFailureLogsFlow = ai.defineFlow(
  {
    name: 'analyzeTestFailureLogsFlow',
    inputSchema: AnalyzeTestFailureLogsInputSchema,
    outputSchema: AnalyzeTestFailureLogsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
